// src/pages/Blog.tsx
import { useState } from 'react';
import { motion } from 'motion/react';
import { Link } from 'react-router-dom';
import { BlogService, BlogPost as BlogPostType } from '@/src/services/blogService';
import { Calendar, User, ArrowRight } from 'lucide-react';
import { AnimatedText } from '@/src/components/ui/AnimatedText';
import { HoverCard } from '@/src/components/ui/HoverCard';

export function Blog() {
  const [posts] = useState<BlogPostType[]>(BlogService.getAllPosts());

  return (
    <div className="relative pt-32 pb-20 px-6 min-h-screen overflow-hidden">
      {/* Background decorations */}
      <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-primary/5 rounded-full blur-[150px] pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-full h-[500px] bg-gradient-to-t from-[#fafafa] to-transparent pointer-events-none z-10" />

      <div className="max-w-7xl mx-auto relative z-20">
        <header className="flex flex-col md:flex-row justify-between items-end gap-8 mb-24 mt-10">
          <div>
            <h1 className="text-5xl md:text-8xl font-display font-bold mb-6 flex items-center">
              <span className="text-dark mr-4">Le</span>
              <span className="text-primary">
                <AnimatedText text="Blog" delay={0.2} />
              </span>
            </h1>
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5, duration: 0.8 }}
              className="text-xl md:text-2xl text-dark/60 max-w-2xl leading-relaxed"
            >
              Actualités, guides et réflexions sur la vie privée et la technologie.
            </motion.p>
          </div>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
          {posts.sort((a, b) => b.date.localeCompare(a.date)).map((post, index) => (
            <motion.article
              key={post.id}
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ delay: index * 0.1, type: "spring", stiffness: 50 }}
              className="h-full"
            >
              <Link to={`/blog/${post.id}`} className="block h-full">
                <HoverCard className="h-full group">
                  <div className="flex flex-col h-full bg-white relative z-10 overflow-hidden">
                    <div className="aspect-video relative overflow-hidden">
                      <div className="absolute inset-0 bg-gradient-to-br from-primary/10 via-transparent to-primary-light/5 group-hover:scale-105 transition-transform duration-700" />
                      <div className="absolute inset-0 bg-noise opacity-5 mix-blend-overlay" />
                      <div className="absolute inset-0 flex items-center justify-center text-dark/10 font-display font-black text-4xl tracking-widest transform -rotate-12 group-hover:rotate-0 group-hover:scale-110 transition-all duration-500">
                          {post.category}
                      </div>
                      <div className="absolute bottom-4 left-4">
                        <span className="px-3 py-1 rounded-full bg-white/80 backdrop-blur-md border border-black/5 text-xs font-bold uppercase tracking-widest text-dark/80">
                          {post.category}
                        </span>
                      </div>
                    </div>
                    
                    <div className="p-8 flex flex-col flex-grow">
                      <div className="flex items-center gap-4 text-xs text-primary mb-4 font-bold uppercase tracking-wider">
                        <span className="flex items-center gap-1.5"><Calendar size={14} /> {post.date}</span>
                        <span className="flex items-center gap-1.5"><User size={14} /> {post.author}</span>
                      </div>
                      
                      <h2 className="text-2xl font-display font-bold mb-4 group-hover:text-primary transition-colors leading-tight text-dark">
                        {post.title}
                      </h2>
                      
                      <p className="text-dark/60 mb-8 line-clamp-3 leading-relaxed flex-grow">
                        {post.excerpt}
                      </p>
                      
                      <div className="inline-flex items-center gap-2 text-dark font-bold group-hover:text-primary transition-colors">
                        <span className="relative overflow-hidden">
                          Lire la suite
                          <span className="absolute bottom-0 left-0 w-full h-[2px] bg-primary -translate-x-full group-hover:translate-x-0 transition-transform duration-300" />
                        </span>
                        <ArrowRight size={18} className="group-hover:translate-x-2 transition-transform duration-300" />
                      </div>
                    </div>
                  </div>
                </HoverCard>
              </Link>
            </motion.article>
          ))}
        </div>
      </div>
    </div>
  );
}

// src/views/Blog.vue
<template>
        
    <div class="min-h-screen pb-20">
        
        <!-- hero -->
        <section class="pt-32 px-4 relative overflow-hidden">

            <div class="absolute top-0 left-0 opacity-20 w-[600px] h-[200px] bg-[#512FEB]/30 rounded-full blur-[120px] -z-1"></div>
            
            <div class="max-w-6xl mx-auto text-center">
                <h1 class="blog-hero-title text-[32px] sm:text-[48px] md:text-[56px] font-bold mb-6">
                    {{  blog_config.blog.title }}
                </h1>
                <p class="text-white/70 text-lg max-w-2xl mx-auto">
                    {{  blog_config.blog.description }}
                </p>
            </div>

        </section>

        <!-- last article -->
        <section 
            class="max-w-6xl mx-auto px-4 mt-20 mb-20 "
        >

            <div 
                @click="router.push(`/blog/${articles[0]?.slug}`)"
                class="
                    blog-card featured-card rounded-xl overflow-hidden 
                    border border-white/10 bg-gradient-to-br 
                    from-[#512FEB]/20 to-transparent backdrop-blur-lg
                    cursor-pointer
                "
            >

                <div class="grid md:grid-cols-2 gap-8 p-8">
                        
                    <div class="rounded-lg overflow-hidden max-h-80 md:h-auto">
                        <img 
                            v-if="articles[0]?.image != 'none'"
                            :src="articles[0]?.image"
                            :alt="articles[0]?.title"
                            class="w-full h-full object-cover"
                        />
                        <img
                            v-else
                            src="../assets/img/file.svg"
                            class="w-full h-full object-contain invert-60"
                        />
                    </div>

                    <div class="flex flex-col justify-center">

                        <div class="flex items-center gap-4 mb-4">

                            <span class="px-3 py-1 bg-[#512FEB]/30 text-[#8B5CF6] rounded-full text-sm font-semibold">
                                {{ articles[0]?.category }}
                            </span>
                            <span class="text-white/60 text-sm">
                                {{ formatDate(articles[0]?.date || '') }}
                            </span>

                        </div>
                        
                        <h2 class="text-[28px] font-bold mb-4">
                            {{ articles[0]?.title }}
                        </h2>
                        <p class="text-white/70 mb-6">
                            {{ articles[0]?.excerpt }}
                        </p>
                        
                        <div class="flex items-center gap-4">
                            
                            <span class="text-white/60">
                                Par {{ articles[0]?.author }}
                            </span>

                            <button 
                                @click="router.push(`/blog/${articles[0]?.slug}`)"
                                class="inline-flex items-center text-[#512FEB] hover:text-[#8B5CF6] transition-colors"
                            >
                                Lire l'article →
                            </button>

                        </div>

                    </div>

                </div>

            </div>

        </section>

        <!-- other's article -->
        <section
            class="max-w-6xl mx-auto px-4 mb-20"
        >

            <h2 class="text-[32px] font-bold mb-12">Articles Récents</h2>
            
            <div class="blog-grid grid md:grid-cols-2 lg:grid-cols-3 gap-8">

                <div
                    v-for="article in articles.slice(1)"
                    :key="article.id"
                    @click="router.push(`/blog/${article.slug}`)"
                    class="
                        blog-card group rounded-xl overflow-hidden border 
                        border-white/10 bg-white/5 hover:bg-white/10 
                        transition-all duration-300 backdrop-blur-lg flex flex-col
                        cursor-pointer
                    "
                >
                    
                    <div class="h-48 overflow-hidden">
                        <img 
                            v-if="article.image !== 'none'"
                            :src="article.image"
                            :alt="article.title"
                            class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-300"
                        />
                        <img
                            v-else
                            src="../assets/img/file.svg"
                            class="w-full h-full object-contain group-hover:scale-110 transition-transform duration-300 invert-50"
                        />
                    </div>

                    
                    <div class="p-6 flex flex-col flex-1">

                        <div class="flex items-center justify-between mb-3">
                        
                            <span class="px-2 py-1 bg-white/10 text-white/60 rounded text-xs font-semibold">
                                {{ article.category }}
                            </span>
                            <span class="text-white/50 text-xs">
                                {{ formatDate(article.date) }}
                            </span>

                        </div>

                        <h3 class="text-lg font-bold mb-2 group-hover:text-[#8B5CF6] transition-colors">
                            {{ article.title }}
                        </h3>

                        <p class="text-white/70 text-sm mb-4 flex-1">
                            {{ article.excerpt }}
                        </p>

                        <div class="flex items-center justify-between pt-4 border-t border-white/10">
                            <span class="text-white/60 text-xs">{{ article.author }}</span>
                            <button 
                                @click="router.push(`/blog/${article.slug}`)"
                                class="text-[#512FEB] hover:text-[#8B5CF6] transition-colors text-sm font-semibold"
                            >
                                →
                            </button>
                        </div>

                    </div>

                </div>

            </div>

        </section>

    </div>

</template>

<script setup lang="ts">
    
import { onMounted } from 'vue';
import blog_config from '../config/blog_config.json';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useRouter } from 'vue-router';

gsap.registerPlugin(ScrollTrigger);

const articles = blog_config.blog.articles;
const router = useRouter();


onMounted(() => {
    
    gsap.fromTo(
        '.blog-hero-title',
        {
            opacity: 0,
            y: 50,
        },
        {
            opacity: 1,
            y: 0,
            duration: 0.8,
            ease: 'power3.out',
        }
    );

    
    gsap.fromTo(
        '.featured-card',
        {
            opacity: 0,
            y: 50,
        },
        {
            opacity: 1,
            y: 0,
            duration: 0.6,
            delay: 0.2,
            ease: 'power3.out',
        }
    );

    
    gsap.fromTo(
        '.blog-grid .blog-card',
        {
            opacity: 0,
            y: 50,
        },
        {
            opacity: 1,
            y: 0,
            duration: 0.6,
            stagger: 0.1,
            delay: 0.4,
            ease: 'power3.out',
        }
    );


    const cards = document.querySelectorAll('.blog-card');

    cards.forEach((card: any) => {
        card.addEventListener('mouseenter', () => {
            gsap.to(card, {
                y: -15,
                boxShadow: '0 20px 40px rgba(81, 47, 235, 0.3)',
                duration: 0.3,
                ease: 'power2.out',
            });
        });

        card.addEventListener('mouseleave', () => {
            gsap.to(card, {
                y: 0,
                boxShadow: '0 5px 15px rgba(0, 0, 0, 0.1)',
                duration: 0.3,
                ease: 'power2.out',
            });
        });
    });

});

const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('fr-FR', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
    });
};

</script>

<style scoped>
.featured-card {
  box-shadow: 0 8px 32px rgba(81, 47, 235, 0.15);
}
</style>
