// src/components/FAQ.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import faq_config from '../config/faq_config.json';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

gsap.registerPlugin(ScrollTrigger);

const faqs = faq_config.faq.faqs;
const activeId = ref<number | null>(null);

const toggleFaq = (id: number) => {
    activeId.value = activeId.value === id ? null : id;
};

onMounted(() => {

    // Animation du titre
    gsap.fromTo(
        '.faq-title',
        {
            opacity: 0,
            y: 50,
        },
        {
            opacity: 1,
            y: 0,
            duration: 0.8,
            ease: 'power3.out',
            scrollTrigger: {
                trigger: '.faq-title',
                start: 'top 80%',
                toggleActions: 'play none none reverse',
            },
        }
    );

    // Animation des items FAQ
    gsap.fromTo(
        '.faq-item',
        {
            opacity: 0,
            x: -30,
        },
        {
            opacity: 1,
            x: 0,
            duration: 0.6,
            stagger: 0.1,
            ease: 'power3.out',
            scrollTrigger: {
                trigger: '.faq-container',
                start: 'top 70%',
                toggleActions: 'play none none reverse',
            },
        }
    );

});

</script>

<template>
        
    <section id="faq" class="py-20 relative overflow-hidden">

        <div class="max-w-4xl mx-auto px-4">
                
            <div class="faq-title text-center mb-16">
                <h2 class="text-[28px] sm:text-[40px] md:text-[50px] font-bold mb-4">
                    {{ faq_config.faq.title }}
                </h2>
                <p class="text-white/70 text-lg">
                    {{ faq_config.faq.description }}
                </p>
            </div>

            <div class="faq-container space-y-4">

                <div
                    v-for="faq in faqs"
                    :key="faq.id"
                    class="faq-item"
                >
                
                <button
                    @click="toggleFaq(faq.id)"
                    class="w-full flex items-center justify-between p-6 rounded-lg border border-white/10 bg-white/5 hover:bg-white/10 transition-all duration-300"
                    :class="{
                        'bg-white/10 border-[#512FEB]/50': activeId === faq.id,
                    }"
                >
                    <span class="text-left font-semibold text-lg text-white">
                        {{ faq.question }}
                    </span>
                    <i
                        class="bi bi-chevron-down transition-transform duration-300"
                        :class="{
                            'rotate-180': activeId === faq.id,
                        }"
                    />
                </button>

                    <transition
                        enter-active-class="transition-all duration-300"
                        enter-from-class="opacity-0 max-h-0"
                        enter-to-class="opacity-100 max-h-96"
                        leave-active-class="transition-all duration-300"
                        leave-from-class="opacity-100 max-h-96"
                        leave-to-class="opacity-0 max-h-0"
                    >
                        <div
                            v-if="activeId === faq.id"
                            class="overflow-hidden"
                        >
                            <div class="p-6 text-white/80 bg-white/5 rounded-b-lg border border-t-0 border-white/10">
                                {{ faq.answer }}
                            </div>
                        </div>
                    </transition>

                </div>
            </div>

            <div class="mt-16 text-center">
                <p class="text-white/70 mb-6">Vous n'avez pas trouvé votre réponse ?</p>
                <a
                    href="/contact"
                    class="inline-flex items-center px-8 py-3 rounded-lg bg-[#512FEB] border border-white/10 text-white hover:bg-[#512FEB]/90 transition-all duration-300 hover:scale-105"
                >
                    Contactez-nous
                    <i class="bi bi-arrow-right ml-2" />
                </a>
            </div>

        </div>

        <div class="absolute bottom-0 right-0 opacity-20 w-[600px] h-[200px] bg-[#512FEB]/30 rounded-full blur-[120px] -z-1"></div>

    </section>

</template>

<style scoped>
section {
  background: linear-gradient(135deg, rgba(81, 47, 235, 0.05) 0%, rgba(0, 0, 0, 0) 100%);
}
</style>

// src/pages/FAQ.tsx
import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { FAQS } from '@/src/constants';
import { ChevronDown, HelpCircle, MessageCircle } from 'lucide-react';
import { Link } from 'react-router-dom';

export function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <div className="pt-32 pb-20 px-6">
      <div className="max-w-4xl mx-auto">
        <header className="text-center mb-20">
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-5xl md:text-7xl font-display font-bold mb-8"
          >
            Besoin d'aide ?
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-xl text-white/50"
          >
            Trouvez les réponses à vos questions sur Silvercore et nos services.
          </motion.p>
        </header>

        <div className="space-y-4">
          {FAQS.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
              className="glass-dark rounded-2xl border-white/5 overflow-hidden"
            >
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="w-full p-6 text-left flex items-center justify-between hover:bg-white/5 transition-colors"
              >
                <span className="text-lg font-bold">{faq.question}</span>
                <ChevronDown
                  className={`text-primary transition-transform duration-300 ${openIndex === index ? 'rotate-180' : ''}`}
                />
              </button>
              <AnimatePresence>
                {openIndex === index && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3 }}
                  >
                    <div className="p-6 text-white/50 leading-relaxed border-t border-white/5">
                      {faq.answer}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>

        <div className="mt-20 p-12 rounded-[2.5rem] glass border-primary/20 text-center">
           <MessageCircle className="mx-auto text-primary mb-6" size={48} />
           <h3 className="text-2xl font-display font-bold mb-4">Vous n'avez pas trouvé votre réponse ?</h3>
           <p className="text-white/50 mb-8">Demandez tout ce qui vous passe par la tête, nous répondons à tout.</p>
           <Link
             to="/contact"
             className="inline-flex bg-primary hover:bg-primary/90 text-white px-8 py-4 rounded-xl font-bold transition-all hover:scale-105"
           >
             Nous contacter
           </Link>
        </div>
      </div>
    </div>
  );
}
